name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt install python3-dev
    - name: Build in release mode
      run: cargo build --verbose --release
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_artifacts-latest
        path: target/release/udpwaf
  build-22:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: sudo apt install python3-dev
    - name: Build in release mode
      run: cargo build --verbose --release
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_artifacts-22
        path: target/release/udpwaf